№1


In [10]:
import numpy as np
m=np.zeros((5,5))
for i in range(5):
  for j in range(5):
    if(i==j+1): m[i,j]+=1
print(m)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


№2

In [2]:
import numpy as np
M = np.random.random((10,3))
print(M)
for i in range(M.shape[0]):
    print(M[i,np.argmin(np.absolute(M[i]-0.5))])

[[0.58983728 0.29711405 0.16570236]
 [0.5708946  0.87363816 0.06597195]
 [0.17150434 0.97852725 0.18839536]
 [0.65796177 0.72215395 0.04822884]
 [0.70408217 0.70018179 0.85803623]
 [0.3278159  0.09628019 0.40848758]
 [0.32791091 0.4235579  0.79037177]
 [0.72099121 0.24644563 0.55291889]
 [0.07341535 0.51731755 0.66871815]
 [0.78659709 0.24834501 0.40346789]]
0.5898372806492531
0.5708946045489168
0.1883953645419829
0.6579617657592554
0.7001817949259617
0.4084875753960383
0.42355790478884736
0.5529188893552001
0.5173175546053945
0.4034678940625044


№3

In [3]:
M = np.random.random((6,6))
print(M)
for i in range(M.shape[0]):
    print(np.sum(M[i])/np.min(M[:,i]))

[[0.24858753 0.44447995 0.87121361 0.76142946 0.8220757  0.81520862]
 [0.5664015  0.56120854 0.73323655 0.8078024  0.91663648 0.52870632]
 [0.34752287 0.3028328  0.86195649 0.40054074 0.09165893 0.48707745]
 [0.0946887  0.09966777 0.41614412 0.24148084 0.49258602 0.60337917]
 [0.03307842 0.95776425 0.47491114 0.39907713 0.37693921 0.28873874]
 [0.94790937 0.83481807 0.34710329 0.95414878 0.84522778 0.06628516]]
119.80605311580617
41.27705188581491
7.17823587925517
8.066671563689669
27.607881555829284
60.277333414899715


№4

In [4]:
m = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
m=[m[i] for i in range(1,m.shape[0]) if (m[i-1]==0)]
print(np.max(m))

5


№5

In [6]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for j in range(x.shape[0]):
    c=0
    for k in range(i.shape[0]): 
        if (i[k]==j): x[j]+=1
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


№6 (1 из, есть куча всяких разных)

In [21]:
import numpy as np
M = np.random.random((10))
print(M)
for i in range(M.shape[0]):
  if(M[i]-round(M[i])>=0.5):
    print(round(M[i])+1)
  else:
    print(round(M[i]))

[0.09668048 0.43274066 0.468611   0.61897898 0.94605995 0.85665303
 0.11944608 0.12704258 0.54103989 0.20823275]
0
0
0
1
1
1
0
0
1
0


№7

In [25]:
def kmeans(a, k, max_iter = 10, theshold = 1e-3,dist = -1):
  N = np.shape(a)[0]
  M = np.shape(a)[1]
  if type (k) == int and k > 0:
    count_centr = k
    centr = a[np.random.choice (N, count_centr, replace = False)]
  else:
    raise
  if (np.shape(centr)[1] != np.shape(a)[1]):
        raise
  x = centr[[np.argmin( np.sum((centr-i)**2, axis = 1)) for i in a]]
  centr, y = np.unique(x, axis=0, return_inverse=True)
  new_centr = np.zeros (np.shape(centr))
  for i in range (N):
    new_centr[y[i]] += a[i]/np.count_nonzero (y==y[i])
  new_dist = np.sum((a - new_centr[y])**2)

  if ( (dist >= 0 and dist - new_dist < theshold) or max_iter == 1):
    return new_centr, new_dist
  return kmeans (a, new_centr, max_iter-1, theshold, new_dist)

проблема с загрузкой датасета(все ломается)